/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiaryRouteImport } from './routes/apiary'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyBatchIdRouteImport } from './routes/verify.$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiaryRoute = ApiaryRouteImport.update({
  id: '/apiary',
  path: '/apiary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyBatchIdRoute = VerifyBatchIdRouteImport.update({
  id: '/verify/$batchId',
  path: '/verify/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apiary': typeof ApiaryRoute
  '/chain': typeof ChainRoute
  '/register': typeof RegisterRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apiary': typeof ApiaryRoute
  '/chain': typeof ChainRoute
  '/register': typeof RegisterRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apiary': typeof ApiaryRoute
  '/chain': typeof ChainRoute
  '/register': typeof RegisterRoute
  '/verify/$batchId': typeof VerifyBatchIdRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/apiary' | '/chain' | '/register' | '/verify/$batchId' | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apiary' | '/chain' | '/register' | '/verify/$batchId' | '/verify'
  id:
    | '__root__'
    | '/'
    | '/apiary'
    | '/chain'
    | '/register'
    | '/verify/$batchId'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiaryRoute: typeof ApiaryRoute
  ChainRoute: typeof ChainRoute
  RegisterRoute: typeof RegisterRoute
  VerifyBatchIdRoute: typeof VerifyBatchIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiary': {
      id: '/apiary'
      path: '/apiary'
      fullPath: '/apiary'
      preLoaderRoute: typeof ApiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$batchId': {
      id: '/verify/$batchId'
      path: '/verify/$batchId'
      fullPath: '/verify/$batchId'
      preLoaderRoute: typeof VerifyBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiaryRoute: ApiaryRoute,
  ChainRoute: ChainRoute,
  RegisterRoute: RegisterRoute,
  VerifyBatchIdRoute: VerifyBatchIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
