/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApiaryRouteImport } from './routes/_authenticated/apiary'
import { Route as AuthenticatedChainRouteImport } from './routes/_authenticated/chain'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedVerifyIndexRouteImport } from './routes/_authenticated/verify.index'
import { Route as AuthenticatedVerifyBatchIdRouteImport } from './routes/_authenticated/verify.$batchId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiaryRoute = AuthenticatedApiaryRouteImport.update({
  id: '/apiary',
  path: '/apiary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChainRoute = AuthenticatedChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyIndexRoute =
  AuthenticatedVerifyIndexRouteImport.update({
    id: '/verify/',
    path: '/verify/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerifyBatchIdRoute =
  AuthenticatedVerifyBatchIdRouteImport.update({
    id: '/verify/$batchId',
    path: '/verify/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/apiary': typeof AuthenticatedApiaryRoute
  '/chain': typeof AuthenticatedChainRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/verify/$batchId': typeof AuthenticatedVerifyBatchIdRoute
  '/verify/': typeof AuthenticatedVerifyIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/apiary': typeof AuthenticatedApiaryRoute
  '/chain': typeof AuthenticatedChainRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/verify/$batchId': typeof AuthenticatedVerifyBatchIdRoute
  '/verify': typeof AuthenticatedVerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apiary': typeof AuthenticatedApiaryRoute
  '/_authenticated/chain': typeof AuthenticatedChainRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/verify/$batchId': typeof AuthenticatedVerifyBatchIdRoute
  '/_authenticated/verify/': typeof AuthenticatedVerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apiary'
    | '/chain'
    | '/register'
    | '/verify/$batchId'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/apiary'
    | '/chain'
    | '/register'
    | '/'
    | '/verify/$batchId'
    | '/verify'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apiary'
    | '/_authenticated/chain'
    | '/_authenticated/register'
    | '/_authenticated/'
    | '/_authenticated/verify/$batchId'
    | '/_authenticated/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apiary': {
      id: '/_authenticated/apiary'
      path: '/apiary'
      fullPath: '/apiary'
      preLoaderRoute: typeof AuthenticatedApiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chain': {
      id: '/_authenticated/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof AuthenticatedChainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify/': {
      id: '/_authenticated/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof AuthenticatedVerifyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify/$batchId': {
      id: '/_authenticated/verify/$batchId'
      path: '/verify/$batchId'
      fullPath: '/verify/$batchId'
      preLoaderRoute: typeof AuthenticatedVerifyBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiaryRoute: typeof AuthenticatedApiaryRoute
  AuthenticatedChainRoute: typeof AuthenticatedChainRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVerifyBatchIdRoute: typeof AuthenticatedVerifyBatchIdRoute
  AuthenticatedVerifyIndexRoute: typeof AuthenticatedVerifyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiaryRoute: AuthenticatedApiaryRoute,
  AuthenticatedChainRoute: AuthenticatedChainRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVerifyBatchIdRoute: AuthenticatedVerifyBatchIdRoute,
  AuthenticatedVerifyIndexRoute: AuthenticatedVerifyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
